// bytecodes: 97

static const label_t bytecodeLabels[] PROGMEM = {
	LABEL(INVOKESHORT),            //   0 - haiku_avr_AVRDefines__BV_II
	LABEL(INVOKESHORT),            //   1 - java_lang_Object__init__V
	LABEL(INVOKESHORT),            //   2 - java_lang_StringBuilder__init__V
	LABEL(INVOKESHORT),            //   3 - ru_timreset_Test_main_YLjava_lang_String_V
	LABEL(INVOKESHORT),            //   4 - haiku_avr_AVRDefines_sei_V
	LABEL(INVOKESHORT),            //   5 - java_lang_Thread_setStateAndSwitch_II
	LABEL(INVOKESHORT),            //   6 - haiku_avr_lib_arduino_ArduinoLib_init_V
	LABEL(INVOKESHORT),            //   7 - haiku_avr_lib_arduino_HaikuMicroKernelEx_init_V
	LABEL(INVOKESHORT),            //   8 - java_lang_Thread_currentThread_Ljava_lang_Thread
	LABEL(INVOKESHORT),            //   9 - haiku_vm_MicroKernel_clinitHaikuMagic_V
	LABEL(INVOKESHORT),            //  10 - java_io_OutputStream__init__V
	LABEL(INVOKESHORT),            //  11 - java_lang_System_getDataAddress_Ljava_lang_Object_I
	LABEL(INVOKESHORT),            //  12 - java_lang_System_identityHashCode_Ljava_lang_Object_I
	LABEL(INVOKESHORT),            //  13 - java_lang_String__init__YCV
	LABEL(INVOKESHORT),            //  14 - java_io_InputStream__init__V
	LABEL(INVOKESHORT),            //  15 - haiku_avr_lib_arduino_HaikuMicroKernelEx_2__init__V
	LABEL(INVOKESHORT),            //  16 - haiku_avr_lib_arduino_HaikuMicroKernelEx_1__init__V
	LABEL(INVOKESHORT),            //  17 - java_io_PrintStream__init__Ljava_io_OutputStream_V
	LABEL(INVOKESHORT),            //  18 - java_lang_String_valueOf_ILjava_lang_String
	LABEL(INVOKESHORT),            //  19 - java_lang_String__init__CV
	LABEL(INVOKESHORT),            //  20 - java_lang_StringBuilder_toString_Ljava_lang_String
	LABEL(INVOKESHORT),            //  21 - java_lang_String_charAt_IC
	LABEL(INVOKESHORT),            //  22 - java_io_PrintStream_print_Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  23 - java_lang_StringBuilder_append_ILjava_lang_StringBuilder
	LABEL(INVOKESHORT),            //  24 - java_lang_StringBuilder_append_Ljava_lang_String_Ljava_lang_StringBuilder
	LABEL(INVOKESHORT),            //  25 - java_io_PrintStream_println_Ljava_lang_String_V
	LABEL(INVOKESHORT),            //  26 - haiku_avr_lib_arduino_HaikuMicroKernelEx_1_write_IV
	LABEL(INVOKESHORT),            //  27 - java_lang_Throwable_toString_Ljava_lang_String
	LABEL(INVOKESHORT),            //  28 - java_io_PrintStream_print_CV
	LABEL(INVOKESHORT),            //  29 - java_lang_String_toString_Ljava_lang_String
	LABEL(INVOKESHORT),            //  30 - java_lang_Object_toString_Ljava_lang_String
	LABEL(INVOKESHORT),            //  31 - java_lang_StringBuilder_append_CLjava_lang_StringBuilder
	LABEL(INVOKESHORT),            //  32 - java_lang_Thread_stop_V
	LABEL(INVOKESHORT),            //  33 - haiku_avr_AVRDefines__clinit__V
	LABEL(INVOKESHORT),            //  34 - main_YLjava_lang_String
	LABEL(INVOKESHORT),            //  35 - java_lang_String_length_I
	LABEL(ARETURN),                //  36 - ARETURN
	LABEL(IFEQ),                   //  37 5 IFNE
	LABEL(IFEQ),                   //  38 6 IFLE
	LABEL(ARRAYLENGTH),            //  39 - ARRAYLENGTH
	LABEL(ALOAD_0),                //  40 0 ALOAD_0
	LABEL(ALOAD_0),                //  41 1 ALOAD_1
	LABEL(ALOAD_0),                //  42 2 ALOAD_2
	LABEL(IFEQ),                   //  43 3 IFGE
	LABEL(BIPUSH),                 //  44 - BIPUSH
	LABEL(IFNONNULL),              //  45 5 IFNONNULL
	LABEL(CALOAD),                 //  46 - CALOAD
	LABEL(CASTORE),                //  47 - CASTORE
	LABEL(FSTORE_0),               //  48 0 ISTORE_0
	LABEL(ASTORE_0),               //  49 1 ASTORE_1
	LABEL(ASTORE_0),               //  50 2 ASTORE_2
	LABEL(IF_ICMPEQ),              //  51 3 IF_ICMPGE
	LABEL(DUP),                    //  52 - DUP
	LABEL(IF_ICMPEQ),              //  53 5 IF_ICMPNE
	LABEL(GETFIELD_I),             //  54 - GETFIELD_I
	LABEL(GETFIELD_L),             //  55 - GETFIELD_L
	LABEL(GETSTATIC_B),            //  56 - GETSTATIC_B
	LABEL(FSTORE_0),               //  57 1 ISTORE_1
	LABEL(IF_ACMPEQ),              //  58 2 IF_ACMPEQ
	LABEL(FSTORE_0),               //  59 3 ISTORE_3
	LABEL(GETSTATIC_L),            //  60 - GETSTATIC_L
	LABEL(LDC_S),                  //  61 5 LDC_S
	LABEL(GOTO),                   //  62 - GOTO
	LABEL(I2C),                    //  63 - I2C
	LABEL(IADD),                   //  64 - IADD
	LABEL(IAND),                   //  65 - IAND
	LABEL(IF_ICMPEQ),              //  66 2 IF_ICMPEQ
	LABEL(ICONST_0),               //  67 - ICONST_0
	LABEL(ICONST_1),               //  68 - ICONST_1
	LABEL(ICONST_2),               //  69 - ICONST_2
	LABEL(ICONST_3),               //  70 - ICONST_3
	LABEL(ICONST_4),               //  71 - ICONST_4
	LABEL(IDIV),                   //  72 - IDIV
	LABEL(IINC1),                  //  73 - IINC1
	LABEL(FSTORE_0),               //  74 2 ISTORE_2
	LABEL(ILOAD),                  //  75 - ILOAD
	LABEL(ILOAD_0),                //  76 - ILOAD_0
	LABEL(ILOAD_1),                //  77 - ILOAD_1
	LABEL(ILOAD_2),                //  78 - ILOAD_2
	LABEL(ILOAD_3),                //  79 - ILOAD_3
	LABEL(INEG),                   //  80 - INEG
	LABEL(INVOKESPECIAL),          //  81 - INVOKESTATIC
	LABEL(INVOKEVIRTUAL),          //  82 - INVOKEVIRTUAL
	LABEL(IOR),                    //  83 - IOR
	LABEL(IREM),                   //  84 - IREM
	LABEL(ARETURN),                //  85 - IRETURN
	LABEL(ISHL),                   //  86 - ISHL
	LABEL(FSTORE),                 //  87 - ISTORE
	LABEL(ISUB),                   //  88 - ISUB
	LABEL(NEW),                    //  89 - NEW
	LABEL(ANEWARRAY),              //  90 - NEWARRAY
	LABEL(POP),                    //  91 - POP
	LABEL(PUTFIELD_L),             //  92 - PUTFIELD_L
	LABEL(PUTSTATIC_B),            //  93 - PUTSTATIC_B
	LABEL(PUTSTATIC_I),            //  94 - PUTSTATIC_I
	LABEL(PUTSTATIC_L),            //  95 - PUTSTATIC_L
	LABEL(RETURN),                 //  96 - RETURN
};
