#if justAsCutAndPastSource__CanBeDonePerClassAlsoWith__javah

/* DO NOT EDIT THIS FILE it is machine generated */
#include <jni.h>
/* Header for all classes */
#ifndef _Included_allClasses
#define _Included_allClasses
#ifdef __cplusplus
extern "C" {
#endif

/////////////////////////////////////////////////


/*
 * Class:     java.lang.System
 * Method:    getDataAddress
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint Java_java_lang_System_getDataAddress
  (JNIEnv *, jclass, jobject);

JNIEXPORT jint Java_java_lang_System_getDataAddress JNICALL
  (JNIEnv *env, jclass obj, jobject arg1)
{
    // TODO: insert your code here
    return 0;
}

/*
 * Proprietary HaikuVM stack to JNI interface function.
 * DO NOT EDIT THIS FUNCTION – it is machine generated.
 * 
 * Class:     java.lang.System
 * Method:    getDataAddress
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT void native_java_lang_System_getDataAddress_Ljava_lang_Object_I(void) {
    pushTop();    // Save variable top onto stack.
    {
        jobject    arg1 = pop()->a;
        jclass     obj = NULL;
        JNIEnv     *env = (JNIEnv*)&top;
        top.s1.i = Java_java_lang_System_getDataAddress(env, obj, arg1);
    }
    // Variable top holds the return value.
}

/////////////////////////////////////////////////


/*
 * Class:     java.lang.Thread
 * Method:    setStateAndSwitch
 * Signature: (I)I
 */
JNIEXPORT jint Java_java_lang_Thread_setStateAndSwitch
  (JNIEnv *, jobject, jint);

JNIEXPORT jint Java_java_lang_Thread_setStateAndSwitch JNICALL
  (JNIEnv *env, jobject obj, jint arg1)
{
    // TODO: insert your code here
    return 0;
}

/*
 * Proprietary HaikuVM stack to JNI interface function.
 * DO NOT EDIT THIS FUNCTION – it is machine generated.
 * 
 * Class:     java.lang.Thread
 * Method:    setStateAndSwitch
 * Signature: (I)I
 */
JNIEXPORT void native_java_lang_Thread_setStateAndSwitch_II(void) {
    pushTop();    // Save variable top onto stack.
    {
        jint    arg1 = pop()->i;
        jobject    obj = pop()->a;
        JNIEnv     *env = (JNIEnv*)&top;
        top.s1.i = Java_java_lang_Thread_setStateAndSwitch(env, obj, arg1);
    }
    // Variable top holds the return value.
}

/////////////////////////////////////////////////


#ifdef __cplusplus
}
#endif
#endif

#endif
